server.port: 7005
server.error.include-message: always

spring.application.name: user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5


spring.data.mongodb:
  host: localhost
  port: 27017
  database: user-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
