server.port: 7005
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: user-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker


server.port: 8080
