api:

  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Natalija
      url: https://github.com/NatalijaGajic
      email: nat.gaj98@mail.com

  course-composite:

    get-composite-course:
      description: Returns a course view of the specified course id
      notes: |
        # Normal response
        If the requested course id is found the method will return information regarding:
        1. Course information
        1. Ratings
        1. Lectures
        1. Service Addresses
        (technical information regarding the addresses of the microservices that created the response)
        # Expected partial and error responses
        1. If no course information is found, a <b>404 - Not Found</b> error will be returned
        1. In no lectures or ratings are found for a course, a partial response will be returned

    create-composite-course:
      description: Creates a composite course
      notes: |
        # Normal response
        The composite product information posted to the API will be splitted up and stored as separate course-info, lecture and rating entities.
        # Expected error responses
        1. If a course with the same courseId as specified in the posted information already exists,
           an <b>422 - Unprocessable Entity</b> error with a "duplicate key" error message will be returned
    delete-composite-course:
      description: Deletes a course composite
      notes: |
        # Normal response
        Entities for course information, lectures and ratings related to the specificed courseId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.
        This means that a delete request of a non existing course will return <b>200 Ok</b>.




server.port: 7000
server.error.include-message: always

spring.application.name: course-composite

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

    
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    output-courses:
      destination: courses
      producer:
        required-groups: auditGroup
    output-lectures:
      destination: lectures
      producer:
        required-groups: auditGroup
    output-ratings:
      destination: ratings
      producer:
        required-groups: auditGroup

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://${app.auth-server}:9999/.well-known/jwks.json


logging:
  level:
    root: INFO
    se.magnus: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.profiles: docker

server.port: 8080

spring.rabbitmq.host: rabbitmq


app:
  eureka-server: eureka
  auth-server: auth-server

spring.cloud.stream.kafka.binder.brokers: kafka